#![allow(unused)] // Ignored for initial setup

//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

pub use super::roles::Entity as Roles;
pub use super::sessions::Entity as Sessions;
pub use super::user_roles::Entity as UserRoles;
pub use super::users::Entity as Users;
