pub struct DocumentationSections {
    pub all: (String, String),
    pub one: (String, String),
    pub create: (String, String),
    pub update: (String, String),
    pub delete: (String, String),
}

impl DocumentationSections {
    /// Converts a list of (endpoint, description) tuples into structured, pre-rendered
    /// HTML sections for documentation.
    ///
    /// The output is intended for embedding into a full HTML page.
    /// Indexes must be in this order:
    /// 1. All items (e.g., `/items/all`)
    /// 2. One item (e.g., `/items/<id>`)
    /// 3. Create item (e.g., `/items/create`)
    /// 4. Update item (e.g., `/items/update/<id>`)
    /// 5. Delete item (e.g., `/items/delete/<id>`)
    pub fn new(sections: &[(&String, &str)]) -> Self {
        let formatted: Vec<String> = sections
            .iter()
            .map(|(endpoint, desc)| format_docs_section(endpoint, desc))
            .collect();

        Self {
            all: (sections[0].1.to_string(), formatted[0].clone()),
            one: (sections[1].1.to_string(), formatted[1].clone()),
            create: (sections[2].1.to_string(), formatted[2].clone()),
            update: (sections[3].1.to_string(), formatted[3].clone()),
            delete: (sections[4].1.to_string(), formatted[4].clone()),
        }
    }
}

/// Formats the documentation section for a given endpoint and description.
pub fn format_docs_section(endpoint: &str, desc: &str) -> String {
    let (title, path, query) = generate_doc_segments(endpoint);
    let path_section = format_params_section(
        "Path Parameters <span class=\"highlight\">&lpar;Required&rpar;</span>",
        &path,
    );
    let query_section = format_params_section("Query Parameters &lpar;Optional&rpar;", &query);
    format!(
        "<h2><code>{}</code></h2><p>{}</p>{}{}",
        title, desc, path_section, query_section
    )
}

fn format_params_section(title: &str, content: &str) -> String {
    if content.trim().is_empty() {
        String::new()
    } else {
        format!("<h3>{title}&colon;</h3><ul>{}</ul>", content.trim())
    }
}

/// Generates documentation segments for a given endpoint.
///
/// Splits the endpoint into (base, path parameters, query parameters).
pub fn generate_doc_segments(endpoint: &str) -> (String, String, String) {
    let base = endpoint.split('?').next().unwrap_or(endpoint).to_string();

    let path = endpoint
        .split('/')
        .filter(|s| s.starts_with('<') && s.ends_with('>'))
        .map(|p| {
            format!(
                "<li><code>{}</code></li>",
                p.trim_matches(|c| c == '<' || c == '>')
            )
        })
        .collect::<Vec<_>>()
        .join("");

    let query = endpoint
        .split('?')
        .nth(1)
        .map(|q| {
            q.split('&')
                .map(|p| {
                    format!(
                        "<li><code>?{}=</code></li>",
                        p.trim_matches(|c| c == '<' || c == '>')
                    )
                })
                .collect::<Vec<_>>()
                .join("")
        })
        .unwrap_or_default();

    (base, path, query)
}

/// Generates top-level HTML documentation for CRUD routes.
///
/// Accepts a top-level endpoint string and a list of (endpoint, description) tuples in this order:
/// 1. All items (e.g., `/items/all`)
/// 2. One item (e.g., `/items/<id>`)
/// 3. Create item (e.g., `/items/create`)
/// 4. Update item (e.g., `/items/update/<id>`)
/// 5. Delete item (e.g., `/items/delete/<id>`)
pub fn generate_docs(endpoint: impl AsRef<str>, routes: &[(&String, &str)]) -> String {
    let sections = DocumentationSections::new(routes);

    let endpoint = endpoint.as_ref();
    let debug_message = if cfg!(debug_assertions) {
        "<p class=\"highlight emphasis\">
            Running in debug mode. This documentation will be displayed without authentication.
        </p>"
    } else {
        ""
    };

    format!(
        r#"
        <style>
            body {{
                font-family: sans-serif;
                margin: 2rem;
                padding: 0;
                background-color: #222;
                color: #fff;
            }}

            h1 {{
                text-align: center;
                border-bottom: solid 2px #ccc;
            }}

            h2 {{
                border-bottom: solid 1px #aaa;
            }}

            .highlight {{
                color: #f88;
            }}

            .emphasis {{
                font-variant: small-caps;
                font-weight: bold;
            }}

            .__hidden {{
                display: none;
            }}
        </style>

        <div class="__hidden">
            This HTML is generated by the `generate_crud_routes` macro.

            If, for some reason, you are trying to read the source code for
            this page, the formatting will be undeniably terrible. I highly
            recommend using your browser's Developer Tools instead. Mostly
            because I *really* don't want to deal with formatting HTML in Rust.
        </div>

        <body class="__docs">
            <h1>CRUD Routes for <code>{endpoint}</code>&colon;</h1>
            {debug_message}
            <h2><code>{endpoint}</code></h2>
            <p>
                Directs admin users to this documentation page.
                Non-admin users will be redirected to <code>{a_trimmed}</code>
                and subsequent redirects will defer to role-based restrictions
                defined as <code class="highlight">
                guards&nbsp;=&nbsp;&lbrace;&nbsp;create&VerticalLine;read&VerticalLine;update&VerticalLine;delete&colon;&nbsp;Path&rbrace;
                </code> in <code class="highlight">
                    &num;&#xfeff;&lsqb;generate_crud_routes&lpar;&rpar;&rsqb;
                </code>
            </p>
            
            {a_docs}
            {o_docs}
            {c_docs}
            {u_docs}
            {d_docs}
        </body>
    "#,
        a_trimmed = sections.all.0.split('?').next().unwrap_or(&sections.all.0),
        a_docs = sections.all.1,
        o_docs = sections.one.1,
        c_docs = sections.create.1,
        u_docs = sections.update.1,
        d_docs = sections.delete.1,
    )
}
